-- Insert products from the menu
-- Execute this after running the main schema

INSERT INTO products (name, price) VALUES
  -- SOPAS
  ('CREME DE ALHO FRANCÊS', 11.00),
  ('CREME DE ESPARGOS COM PRESUNTO FRITO', 18.00),
  -- BACALHAU
  ('ESPINAFRES GRATINADOS COM CAMARÃO', 50.00),
  ('BACALHAU ESPIRITUAL', 34.00),
  ('BACALHAU DAS OLGUINHAS', 36.00),
  ('BACALHAU COM BROA E COENTROS', 50.00),
  -- CARNE
  ('LOMBO DE VACA COM MOLHO DE VINHO DA MADEIRA', 83.00),
  ('ROSBIFE COM MOLHO DE VINHO DA MADEIRA', 71.00),
  ('PERU RECHEADO', 44.00),
  ('PERU SEM RECHEIO', 41.00),
  ('PERNA DE PERÚ COM RECHEIO À PARTE', 45.00),
  ('RECHEIO DO PERU', 30.00),
  -- ACOMPANHAMENTOS
  ('ESPINAFRES À LÁ CREME', 28.00),
  ('BATATINHAS A MURRO NO FORNO', 22.00),
  ('ARROZ ÁRABE', 34.00),
  ('ARROZ ESCURO', 15.00),
  ('CASTANHAS CARAMELIZADAS', 34.00),
  ('BATATA PALHA', 36.00),
  -- SOBREMESAS
  ('BOLO DE CHOCOLATE', 42.00),
  ('SUSPIRO COM CHOCOLATE', 42.00),
  ('SUSPIRO COM DOCE DE OVOS E AMENDOA', 42.00),
  ('TARTE DE LIMA', 39.00),
  ('BLOTTERTORTE', 42.00),
  ('MARQUISE DE CHOCOLATE', 35.00),
  ('LÉRIAS', 2.00),
  ('PAPÃO DE ANJO', 42.00),
  ('PAPOS DE ANJO', 3.00),
  ('TARTE DE MAÇÃ', 42.00)
ON CONFLICT (name) DO NOTHING;

